### ISSUE TITLE
AT&T Uverse Control

### ISSUE THREAD

**Issue by kvarga** [dgomes/pymediaroom#5]
Any idea what needs to be done (if possible) to control a Uverse with this? Seems like I can get the status correctly (PLAYING_LIVE_TV), but get some exceptions when trying to run any command

```
$ python app.py
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:pymediaroom.notify:0.6.3
DEBUG:pymediaroom.remote:Found: 192.168.1.86
DEBUG:pymediaroom.remote:Found: 192.168.1.233
DEBUG:pymediaroom.remote:Found: 192.168.1.73
DEBUG:pymediaroom.notify:Closing MediaroomProtocol
DEBUG:pymediaroom.remote:discover() timeout!
INFO:root:Found ['192.168.1.233', '192.168.1.73', '192.168.1.86']
DEBUG:pymediaroom.notify:0.6.3
DEBUG:pymediaroom.remote:NOTIFY from 192.168.1.86 - None
DEBUG:pymediaroom.remote:NOTIFY from 192.168.1.233 - OrderedDict([('@src', 'udp://239.192.14.32:7534:64d73ea4-b66a-4c38-8750-a39d6dc4bda1'), ('@pipe', 'FULLSCREEN'), ('@ct', '0xdf085076ead1ab58'), ('@pil', '0x0'), ('@rate', '0x5816c5'), ('@stopped', 'false')])
DEBUG:pymediaroom.remote:192.168.1.233 is State.PLAYING_LIVE_TV
DEBUG:pymediaroom.remote:NOTIFY from 192.168.1.73 - OrderedDict([('@src', 'udp://239.192.14.32:7534:64d73ea4-b66a-4c38-8750-a39d6dc4bda1'), ('@rate', '0x5816c5'), ('@pil', '0x0')])
DEBUG:pymediaroom.remote:NOTIFY from 192.168.1.86 - None
DEBUG:pymediaroom.remote:NOTIFY from 192.168.1.233 - OrderedDict([('@src', 'udp://239.192.14.32:7534:64d73ea4-b66a-4c38-8750-a39d6dc4bda1'), ('@pipe', 'FULLSCREEN'), ('@ct', '0xdf085079eb9646fe'), ('@pil', '0x0'), ('@rate', '0x5816c5'), ('@stopped', 'false')])
DEBUG:pymediaroom.remote:192.168.1.233 is State.PLAYING_LIVE_TV
DEBUG:pymediaroom.remote:NOTIFY from 192.168.1.73 - OrderedDict([('@src', 'udp://239.192.14.32:7534:64d73ea4-b66a-4c38-8750-a39d6dc4bda1'), ('@rate', '0x5816c5'), ('@pil', '0x0')])
DEBUG:pymediaroom.remote:turn_on while State.PLAYING_LIVE_TV
INFO:pymediaroom.remote:Send cmd = Rose
DEBUG:pymediaroom.remote:Connecting to 192.168.1.233:8086
DEBUG:pymediaroom.remote:NOTIFY from 192.168.1.86 - None
DEBUG:pymediaroom.remote:NOTIFY from 192.168.1.233 - OrderedDict([('@src', 'udp://239.192.14.32:7534:64d73ea4-b66a-4c38-8750-a39d6dc4bda1'), ('@pipe', 'FULLSCREEN'), ('@ct', '0xdf08507cec5ae2a4'), ('@pil', '0x0'), ('@rate', '0x5816c5'), ('@stopped', 'false')])
DEBUG:pymediaroom.remote:192.168.1.233 is State.PLAYING_LIVE_TV
DEBUG:pymediaroom.remote:NOTIFY from 192.168.1.73 - OrderedDict([('@src', 'udp://239.192.14.32:7534:64d73ea4-b66a-4c38-8750-a39d6dc4bda1'), ('@rate', '0x5816c5'), ('@pil', '0x0')])
DEBUG:pymediaroom.remote:NOTIFY from 192.168.1.86 - None
DEBUG:pymediaroom.remote:NOTIFY from 192.168.1.233 - OrderedDict([('@src', 'udp://239.192.14.32:7534:64d73ea4-b66a-4c38-8750-a39d6dc4bda1'), ('@pipe', 'FULLSCREEN'), ('@ct', '0xdf08507fed1f7e4a'), ('@pil', '0x0'), ('@rate', '0x5816c5'), ('@stopped', 'false')])
DEBUG:pymediaroom.remote:192.168.1.233 is State.PLAYING_LIVE_TV
DEBUG:pymediaroom.remote:NOTIFY from 192.168.1.73 - OrderedDict([('@src', 'udp://239.192.14.32:7534:64d73ea4-b66a-4c38-8750-a39d6dc4bda1'), ('@rate', '0x5816c5'), ('@pil', '0x0')])
WARNING:pymediaroom.remote:
Traceback (most recent call last):
  File "/Users/kylevarga/Code/personal/test/pymediaroom/pymediaroom/remote.py", line 78, in send_cmd
    await stb_recv.read(6)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/streams.py", line 634, in read
    yield from self._wait_for_data('read')
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/streams.py", line 464, in _wait_for_data
    yield from self._waiter
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kylevarga/Code/personal/test/pymediaroom/pymediaroom/remote.py", line 85, in send_cmd
    await asyncio.sleep(0.300)
  File "/Users/kylevarga/Code/personal/test/pymediaroom/env/lib/python3.6/site-packages/async_timeout/__init__.py", line 55, in __aexit__
    self._do_exit(exc_type)
  File "/Users/kylevarga/Code/personal/test/pymediaroom/env/lib/python3.6/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 39, in <module>
    loop.run_until_complete(main(loop))
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "app.py", line 21, in main
    await remote.send_cmd('Rose') 
  File "/Users/kylevarga/Code/personal/test/pymediaroom/pymediaroom/remote.py", line 89, in send_cmd
    raise PyMediaroomError("Timeout connecting to {}".format(self.stb_ip))
pymediaroom.error.PyMediaroomError: Timeout connecting to 192.168.1.233```

I've attempted changing port in app.py to match nmap response, but same stacktrace as above. 
```
$ nmap -A -Pn 192.168.1.233 
Starting Nmap 7.70 ( https://nmap.org ) at 2018-07-29 09:32 CDT
Nmap scan report for 192.168.1.233
Host is up (0.016s latency).
Not shown: 998 closed ports
PORT     STATE SERVICE VERSION
8080/tcp open  http    T-Home Telekom Media Receiver httpd
|_http-title: Site doesn't have a title.
8086/tcp open  http    Microsoft Mediaroom httpd (IPTV tuner)
|_http-title: Site doesn't have a title.
Service Info: Device: media device

Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 17.35 seconds
```

**Comment by dgomes** [comment]
Hi! 

I don't have access to those boxes. Do you have a mobile app from which you can control the STB ? try using wireshark to check what it does :)

**Comment by kvarga** [comment]
Will try it out, I believe the mobile app runs through AT&T's servers, not
direct to these boxes.

--
Kyle Varga

**Comment by dgomes** [comment]
This implementation targets deployments where the mobile app can control directly the box...

Will accept PR if you come up with a solution :)

**Comment by waltlillyman** [comment]
And I can help test a solution for AT&T Uverse, I have three of their STBs and would love to make Home Assistant work directly with them.
